[package]
name = "browser-tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boring = "3.0.4"
boring-sys = "3.0.4"
reqwest = "0.11.20"
